dtx <- dt2
dtx$Africa <- ifelse(dtx$Continent == "Africa", 1, 0)
dtx$Asia <- ifelse(dtx$Continent == "Asia", 1, 0)
dtx$Australia <- ifelse(dtx$Continent == "Australia", 1, 0)
dtx$Europe <- ifelse(dtx$Continent == "Europe", 1, 0)
dtx$SouthAmerica <- ifelse(dtx$Continent == "South America", 1, 0)

dtx$Argentina <- ifelse(dtx$Country == "Argentina", 1, 0)      
dtx$Australia1 <- ifelse(dtx$Country == "Australia", 1, 0)          
dtx$Brazil <- ifelse(dtx$Country == "Brazil", 1, 0) 
dtx$Canada <- ifelse(dtx$Country == "Canada", 1, 0) 
dtx$China <- ifelse(dtx$Country == "China", 1, 0) 
dtx$Colombia <- ifelse(dtx$Country == "Colombia", 1, 0) 
dtx$France <- ifelse(dtx$Country == "France", 1, 0)        
dtx$Germany <- ifelse(dtx$Country == "Germany", 1, 0)           
dtx$India <- ifelse(dtx$Country == "India", 1, 0)           
dtx$Italy <- ifelse(dtx$Country == "Italy", 1, 0) 
dtx$Japan <- ifelse(dtx$Country == "Japan", 1, 0)     
dtx$NewZealand <- ifelse(dtx$Country == "New Zealand", 1, 0)         
dtx$Nigeria <- ifelse(dtx$Country == "Nigeria", 1, 0)    
dtx$SouthAfrica <- ifelse(dtx$Country == "South Africa", 1, 0)     
dtx$SouthKorea <- ifelse(dtx$Country == "South Korea", 1, 0) 
dtx$Spain <- ifelse(dtx$Country == "Spain", 1, 0)        
dtx$Thailand <- ifelse(dtx$Country == "Thailand", 1, 0)  
dtx$UK <- ifelse(dtx$Country == "United Kingdom", 1, 0)   
dtx$Vietnam <- ifelse(dtx$Country == "Vietnam", 1, 0) 
